# @package _global_

defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

checkpoint:
  path: "./trained_models/unet-cond-ca-bs512-150K-cpd25"

  global_step: null
  use_non_ema: false

sampling:
  seed: 42
  contexts_file: "./samples/contexts/random_synthetic_uniform_5000.npy"

  batch_size: 50
  n_contexts: 5 # 10050

  n_samples_per_context: 4 #50

hydra:
  output_subdir: null
  run:
    dir: .